### ISSUE TITLE
[BUG] error querying index with a field having empty json objects with connector elasticsearch

### ISSUE THREAD

**Issue by madhavvishnubhatta** [awslabs/aws-athena-query-federation#423] opened 2021-06-02 13:42 UTC
**Describe the bug**
I get an error `Detected unsupported type[Struct / STRUCT for column` when trying to query indices with empty json objects as a sub-element.

**To Reproduce**
1. Create an index in Elasticsearch using the Kibana dev tools interface with the following command
```
PUT /testindex
{
 "mappings": {
   "properties": {
    "col1": {"type": "object"}
  }
 }
}
```
2. Add a single document to the index with the command below
```
POST /testindex/_doc
{
"col1": {
        "somedata": {}
      }
}
```
3. Query the index from Athena with the following query
```sql
select count(*) from "lambda:elasticsearch"."testdomain"."testindex"
```
```
GENERIC_USER_ERROR: Encountered an exception[java.lang.RuntimeException] from your LambdaFunction[elasticsearch] executed in context[retrieving meta-data] with message[Detected unsupported type[Struct / STRUCT for column[col1]]
```

**Expected behavior**
Athena should return a value of 1

**Screenshots / Exceptions / Errors**
```
2021-06-02 13:30:18 2219530a-2757-4504-89f8-40467ad3740c WARN  ElasticsearchMetadataHandler:245 - doGetTable: Unable to retrieve table[cloudtrail-es:testindex5] from AWS Glue.
com.amazonaws.services.glue.model.EntityNotFoundException: Database cloudtrail-es not found. (Service: AWSGlue; Status Code: 400; Error Code: EntityNotFoundException; Request ID: 1f3605a4-d194-4307-9b7c-a6917e5dd63d; Proxy: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1811) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1395) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1371) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530) ~[task/:?]
	at com.amazonaws.services.glue.AWSGlueClient.doInvoke(AWSGlueClient.java:8202) ~[task/:?]
	at com.amazonaws.services.glue.AWSGlueClient.invoke(AWSGlueClient.java:8169) ~[task/:?]
	at com.amazonaws.services.glue.AWSGlueClient.invoke(AWSGlueClient.java:8158) ~[task/:?]
	at com.amazonaws.services.glue.AWSGlueClient.executeGetTable(AWSGlueClient.java:4774) ~[task/:?]
	at com.amazonaws.services.glue.AWSGlueClient.getTable(AWSGlueClient.java:4745) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.GlueMetadataHandler.doGetTable(GlueMetadataHandler.java:347) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.GlueMetadataHandler.doGetTable(GlueMetadataHandler.java:325) ~[task/:?]
	at com.amazonaws.connectors.athena.elasticsearch.ElasticsearchMetadataHandler.doGetTable(ElasticsearchMetadataHandler.java:240) [task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doHandleRequest(MetadataHandler.java:250) [task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:132) [task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:100) [task/:?]
	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:902) [LambdaSandboxJava-1.0.jar:?]
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:340) [LambdaSandboxJava-1.0.jar:?]
	at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63) [LambdaSandboxJava-1.0.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_201]
	at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:150) [LambdaJavaRTEntry-1.0.jar:?]

2021-06-02 13:30:18 2219530a-2757-4504-89f8-40467ad3740c WARN  CompositeHandler:104 - handleRequest: Completed with an exception.
java.lang.RuntimeException: Detected unsupported type[Struct / STRUCT for column[col1]
	at com.amazonaws.athena.connector.lambda.data.SupportedTypes.assertSupported(SupportedTypes.java:128) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.assertTypes(MetadataHandler.java:478) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doHandleRequest(MetadataHandler.java:253) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:132) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:100) [task/:?]
	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:902) [LambdaSandboxJava-1.0.jar:?]
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:340) [LambdaSandboxJava-1.0.jar:?]
	at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63) [LambdaSandboxJava-1.0.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_201]
	at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:150) [LambdaJavaRTEntry-1.0.jar:?]

Detected unsupported type[Struct / STRUCT for column[col1]: java.lang.RuntimeException
java.lang.RuntimeException: Detected unsupported type[Struct / STRUCT for column[col1]
	at com.amazonaws.athena.connector.lambda.data.SupportedTypes.assertSupported(SupportedTypes.java:128)
	at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.assertTypes(MetadataHandler.java:478)
	at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doHandleRequest(MetadataHandler.java:253)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:132)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:100)
```

**Connector Details (please complete the following information):**
 - Version: `2021.18.1`
 - Name: `Elasticsearch`
 - Athena Query IDs: `a7910f06-5053-4be0-85e1-9b7ddc51d2b0`

**Additional context**
When I re-create the index and then add a document with a non-empty sub-element as below, it works fine:
```
DELETE /testindex
```
```
PUT /testindex
{
 "mappings": {
   "properties": {
    "col1": {"type": "object"}
  }
 }
}
```
```
POST /testindex/_doc
{
"col1": {
        "somedata": {"a":"b"}
      }
}
```

**Comment by nauy2697** [comment] 2022-10-24 18:20
Hi,

Thanks for reaching out and sorry to hear you have issue with elasticsearch connector. 

Upon investigation, the root cause of issue is due to schema inference for `col`.`somedata` sub field. Due to it is empty, our schema inference has no mechanism to figure out what is the data type for this sub field. This is a limitation as our schema inference need data to identify the proper data types.

To by-pass the issue, we recommend to set up supplemental data schema in glue. Please visit the manual below 
https://docs.aws.amazon.com/athena/latest/ug/connectors-opensearch.html under the section of `Setting up databases and tables in AWS Glue`

**Comment by nauy2697** [comment] 2022-10-31 16:11
Hi,

Thanks for reaching out on the issue. Since this issue is specific to the user's data and schemas set up. I will close this ticket. If you have further questions feel free to reach out or reopen.

Thanks

**Closed by nauy2697** 2022-10-31 16:11 UTC
Labels: bug
