### ISSUE TITLE
[BUG] connection timed out with connector BigQuery Athena custom connector

### ISSUE THREAD

**Issue by gubaruch** [awslabs/aws-athena-query-federation#737] opened 2022-07-21 22:00 UTC
**Describe the bug**
going through the steps of creating a custom connector to google big query , and creating a parallel a GCP account , I went and validated the configurations , which are all correct.

when running the athena query , I am waiting for about 4.5 min and then getting the following : 

com.google.cloud.bigquery.BigQueryException: Error getting access token for service account: connect timed out

**To Reproduce**

**Expected behavior**
once the lambda function would connect to the relevant BQ dataset , data should be retrieved and the result show be observed on the Athena UI side 

**Screenshots / Exceptions / Errors**

ERROR BigQueryUtils:142 - Error:
com.google.cloud.bigquery.BigQueryException: Error getting access token for service account: connect timed out
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:106) ~[task/:?]
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.listDatasets(HttpBigQueryRpc.java:146) ~[task/:?]
	at com.google.cloud.bigquery.BigQueryImpl$7.call(BigQueryImpl.java:405) ~[task/:?]
	at com.google.cloud.bigquery.BigQueryImpl$7.call(BigQueryImpl.java:401) ~[task/:?]
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105) ~[task/:?]
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76) ~[task/:?]
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50) ~[task/:?]
	at com.google.cloud.bigquery.BigQueryImpl.listDatasets(BigQueryImpl.java:399) ~[task/:?]
	at com.google.cloud.bigquery.BigQueryImpl.listDatasets(BigQueryImpl.java:390) ~[task/:?]
	at com.amazonaws.athena.connectors.google.bigquery.BigQueryUtils.fixCaseForDatasetName(BigQueryUtils.java:131) [task/:?]
	at com.amazonaws.athena.connectors.google.bigquery.BigQueryMetadataHandler.getSchema(BigQueryMetadataHandler.java:253) [task/:?]
	at com.amazonaws.athena.connectors.google.bigquery.BigQueryMetadataHandler.doGetTable(BigQueryMetadataHandler.java:163) [task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doHandleRequest(MetadataHandler.java:257) [task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:135) [task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:103) [task/:?]
	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:899) [aws-lambda-java-runtime-0.2.0.jar:?]
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:268) [aws-lambda-java-runtime-0.2.0.jar:?]
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:206) [aws-lambda-java-runtime-0.2.0.jar:?]
	at lambdainternal.AWSLambda.main(AWSLambda.java:200) [aws-lambda-java-runtime-0.2.0.jar:?]
Caused by: java.io.IOException: Error getting access token for service account: connect timed out
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:360) ~[task/:?]
	at com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:165) ~[task/:?]
	at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:151) ~[task/:?]
	at com.google.auth.http.HttpCredentialsAdapter.initialize(HttpCredentialsAdapter.java:96) ~[task/:?]
	at com.google.cloud.http.HttpTransportOptions$1.initialize(HttpTransportOptions.java:159) ~[task/:?]
	at com.google.api.client.http.HttpRequestFactory.buildRequest(HttpRequestFactory.java:88) ~[task/:?]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:430) ~[task/:?]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:549) ~[task/:?]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:482) ~[task/:?]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:599) ~[task/:?]
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.listDatasets(HttpBigQueryRpc.java:138) ~[task/:?]
	... 17 more
Caused by: java.net.SocketTimeoutException: connect timed out
	at [java.net](http://java.net/).PlainSocketImpl.socketConnect(Native Method) ~[?:?]
	at [java.net](http://java.net/).AbstractPlainSocketImpl.doConnect(Unknown Source) ~[?:?]
	at [java.net](http://java.net/).AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[?:?]
	at [java.net](http://java.net/).AbstractPlainSocketImpl.connect(Unknown Source) ~[?:?]
	at [java.net](http://java.net/).SocksSocketImpl.connect(Unknown Source) ~[?:?]
	at [java.net](http://java.net/).Socket.connect(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source) ~[?:?]
	at [sun.net](http://sun.net/).NetworkClient.doConnect(Unknown Source) ~[?:?]
	at [sun.net](http://sun.net/).[www.http.HttpClient.openServer](http://www.http.httpclient.openserver/)(Unknown Source) ~[?:?]
	at [sun.net](http://sun.net/).[www.http.HttpClient.openServer](http://www.http.httpclient.openserver/)(Unknown Source) ~[?:?]
	at [sun.net](http://sun.net/).[www.protocol.https.HttpsClient](http://www.protocol.https.httpsclient/).<init>(Unknown Source) ~[?:?]
	at [sun.net](http://sun.net/).[www.protocol.https.HttpsClient.New](http://www.protocol.https.httpsclient.new/)(Unknown Source) ~[?:?]
	at [sun.net](http://sun.net/).[www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient](http://www.protocol.https.abstractdelegatehttpsurlconnection.getnewhttpclient/)(Unknown Source) ~[?:?]
	at [sun.net](http://sun.net/).[www.protocol.http.HttpURLConnection.plainConnect0](http://www.protocol.http.httpurlconnection.plainconnect0/)(Unknown Source) ~[?:?]
	at [sun.net](http://sun.net/).[www.protocol.http.HttpURLConnection.plainConnect](http://www.protocol.http.httpurlconnection.plainconnect/)(Unknown Source) ~[?:?]
	at [sun.net](http://sun.net/).[www.protocol.https.AbstractDelegateHttpsURLConnection.connect](http://www.protocol.https.abstractdelegatehttpsurlconnection.connect/)(Unknown Source) ~[?:?]
	at [sun.net](http://sun.net/).[www.protocol.http.HttpURLConnection.getOutputStream0](http://www.protocol.http.httpurlconnection.getoutputstream0/)(Unknown Source) ~[?:?]
	at [sun.net](http://sun.net/).[www.protocol.http.HttpURLConnection.getOutputStream](http://www.protocol.http.httpurlconnection.getoutputstream/)(Unknown Source) ~[?:?]
	at [sun.net](http://sun.net/).[www.protocol.https.HttpsURLConnectionImpl.getOutputStream](http://www.protocol.https.httpsurlconnectionimpl.getoutputstream/)(Unknown Source) ~[?:?]
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:108) ~[task/:?]
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:79) ~[task/:?]
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:995) ~[task/:?]
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:358) ~[task/:?]
	at com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:165) ~[task/:?]
	at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:151) ~[task/:?]
	at com.google.auth.http.HttpCredentialsAdapter.initialize(HttpCredentialsAdapter.java:96) ~[task/:?]
	at com.google.cloud.http.HttpTransportOptions$1.initialize(HttpTransportOptions.java:159) ~[task/:?]
	at com.google.api.client.http.HttpRequestFactory.buildRequest(HttpRequestFactory.java:88) ~[task/:?]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:430) ~[task/:?]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:549) ~[task/:?]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:482) ~[task/:?]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:599) ~[task/:?]
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.listDatasets(HttpBigQueryRpc.java:138) ~[task/:?]
	... 17 more

**Connector Details (please complete the following information):**
 - Version: 2022.24.1
 - Name AthenaGoogleBigQueryConnector 
 - Athena Query IDs [if applicable]

**Additional context**
this is a major ask from 2 large telco customers who are looking to leverage the athena connector pull relevant datasets in BQ to AWS and build data governance on top .

**Comment by henrymai** [comment] 2022-08-16 18:51
@gubaruch

Internally confirmed that he was able to get it working. Closing this issue out now.

**Closed by henrymai** 2022-08-16 18:51 UTC
Labels: bug

**Comment by nilic-ideacompiler** [comment] 2023-01-12 14:41
We have same problem, can we get how he was able to get it working?

**Comment by iainelder** [comment] 2023-01-26 15:11
@henrymai , please share details of the solution.

I'm facing exactly this problem when trying to use the connector for the first time.

I see a recent GitHub issue about support for a "private endpoint" that sounds promising. But I see no guidance on how to use it.

https://github.com/awslabs/aws-athena-query-federation/pull/835

**Comment by henrymai** [comment] 2023-01-26 15:25
@iainelder @nilic-ideacompiler Can you guys try removing the VPC from the BigQuery Connector Lambda? I think that's been a common issue with users that I've seen (I wasn't given any actual details from @gubaruch to tell you exactly what he did to fix it).

**Comment by henrymai** [comment] 2023-01-26 16:53
> Is the intention of this to give the Lambda access to the public internet?

Yes, because the Lambda needs public internet access to reach BigQuery, which is hosted on the public internet.

> To "remove the VPC", do I omit the subnet IDs from the configuration?

No, since you've already deployed the BigQuery connector, I'm suggesting that you just go to the AWS Lambda Console, and click on the lambda for the bigquery connector and then just remove the VPC from the configuration.

In regards to omitting the subnet during deployment, the current `athena-google-bigquery.yaml` is not written well and will unfortunately force you to set it even though it is not necessary, which is what causes your lambda to sit within a vpc in the first place and is causing this problem.

**Comment by iainelder** [comment] 2023-01-26 17:02
Thank you so much for the advice. I'll try it soon and let you know how it goes.

**Comment by henrymai** [comment] 2023-01-26 20:21
@iainelder and @nilic-ideacompiler 
Here's a patch to fix the issue with the template forcing users to set the subnets and security groups: https://github.com/awslabs/aws-athena-query-federation/pull/993

**Comment by iainelder** [comment] 2023-01-27 08:51
To remove the VPC, I did the following:

* Go the Lambda console
* View the connector Lambda (called `bigquery_public_data` in my environment)
* Go to the Configuration tab
* Go to the VPC section
* Click Edit
* VPC: None
* Click Save

Now the VPC section shows:

> No VPC configuration
>
> This function isn't connected to a VPC.

To check the behavior I executed the following query: `show schemas in bigquery_public_data`.

By absence of errors, the log shows a successful connection to Google services!

(I've omitted the request and query identifiers from the log extract.)

```log
START RequestId: ... Version: $LATEST
2023-01-26 17:23:25 ... INFO  MetadataHandler:239 - doHandleRequest: request[ListSchemasRequest{queryId=...}]
2023-01-26 17:23:25 ... INFO  BigQueryMetadataHandler:85 - doListSchemaNames called with Catalog: bigquery_public_data
2023-01-26 17:23:27 ... INFO  BigQueryMetadataHandler:106 - Found 0 schemas!
2023-01-26 17:23:27 ... INFO  MetadataHandler:244 - doHandleRequest: response[ListSchemasResponse{schemas=[]}]
2023-01-26 17:23:27 ... DEBUG BlockAllocatorImpl:234 - closeBatches: 0
2023-01-26 17:23:27 ... DEBUG BlockAllocatorImpl:198 - closeBlocks: 0
2023-01-26 17:23:27 ... DEBUG BlockAllocatorImpl:216 - closeBuffers: 0
END RequestId: ...
REPORT RequestId: ...	Duration: 1710.61 ms	Billed Duration: 1711 msMemory Size: 3008 MB	Max Memory Used: 200 MB	
```

Thanks, @henrymai, for your quick response and guidance.

**Comment by iainelder** [comment] 2023-01-27 09:02
Thanks for the patch in #993. I won't try it immediately since I already have solved the problem in the console. But if I repeat the setup from scratch I'll be sure to try deploying the Lambda without setting subnets and security groups to see whether it works for me.

While running without a customer VPC does appear to solve the problem, it does open things up perhaps too much for comfort.

To my list of of possible solutions I would add another, perhaps more simple option:

* Add a rule to the connector security group for outbound access to [IP ranges that Google makes available to users on the internet](https://www.gstatic.com/ipranges/goog.json).

More information about Google IP ranges is available in [Google Workspace Admin Help](https://support.google.com/a/answer/10026322?hl=en).

If I need more help with any of above, I'll open a new issue. Thanks again!
