### ISSUE TITLE
[BUG] DocumentDB connector can't handle collections with uppercase letters

### ISSUE THREAD

**Issue by alFReD-NSH** [awslabs/aws-athena-query-federation#463] opened 2021-07-27 13:41 UTC
If the collection name has an uppercase letter, querying it will result in an error.

**To Reproduce**
1. Set up DocumentDB and the DocumentDB connector for Athena.
2. Insert a document into a collection with a uppercase letter in the name in DocumentDB: `db.T1.insert({})`
3. In Athena, query the collection: `select * from T1`

**Expected behavior**
Either the query should happen successfully(attempt the test without uppercase letters), or the project documentation should mention this as a limitation.

```
Your query has the following error(s):

NOT_SUPPORTED: Table has no columns: documentdb:com.amazonaws.presto.connectors.lambda.handles.LambdaTableHandle@5e78097a

This query ran against the "test" database, unless qualified by the query. Please post the error message on our forum or contact customer support with Query Id: f8831726-435a-4041-ae49-35a737a35c8e.
```

**Connector Details (please complete the following information):**
 - Version: 2021.27.1
 - Name: AthenaDocumentDBConnector
 - Athena Query IDs: f8831726-435a-4041-ae49-35a737a35c8e

**Additional context**

We are using Spring framework to write DocumentDB and by default it uses the Java class name appended with Entity as the collection name, for exmaple for a class name Record, the Documentdb collection would be recordEntity by default.

**Comment by avirtuos** [comment] 2021-08-12 13:13
Athena is not case sensitive total which results odd behavior when federating to a source that is case sensitive.  At present there are two options available: 1) use the Connector specific instructions for supplying supplemental meta-data (e.g. name mappings) via Glue Data Catalog or 2) rename the entities to all be lower cases.

This is on our radar as something we want to further enhance to avoid the burden on Customers but its not close enough to being available where I can offer it as a temporary patch.

**Comment by jinman** [comment] 2022-08-15 20:41
Hi @avirtuos,

We have this problem with neptune and dynamodb connectors as well. Is there example on how do we fix using the solution you mentioned "1) use the Connector specific instructions for supplying supplemental meta-data (e.g. name mappings) via Glue Data Catalog"

How do we provide meta-data for dynamodb/neptune connector in Glue Catalog?

Thank you in advance!

**Comment by henrymai** [comment] 2022-08-15 20:59
Hi @jinman

There's a new feature that might take care of your problem: https://github.com/awslabs/aws-athena-query-federation/tree/master/athena-dynamodb#disable_projection_and_casing

Its a new environment variable on the lambda, where you should set the value to "always".

**Comment by henrymai** [comment] 2022-08-15 21:02
Hi @jinman

We have a new feature for the DynamoDB Connector that should resolve your issue: https://github.com/awslabs/aws-athena-query-federation/tree/master/athena-dynamodb#disable_projection_and_casing

You should set that environment variable on your lambda to "always" and things should work for you even if your DynamoDB table contains casing.

This is not implemented on any other connector yet though.

**Comment by salieri** [comment] 2022-08-24 18:36
@henrymai Since the `disable_projection_and_casing` flag is not available for DocDB and there seems to be no column mapping support for the DocDB connector, does that mean that anyone using DocDB cannot use Glue if their column names are not in lower case?

**Comment by henrymai** [comment] 2022-08-24 18:43
@salieri

Yes, that is a current limitation of the DocDB Connector.

**Comment by salieri** [comment] 2022-08-24 18:51
@henrymai Can you reopen this issue? It seems like a fair assumption that I'm not the only one stuck with a schema that's not in lowercase and no remedy available...

**Comment by henrymai** [comment] 2022-08-24 18:56
I wasn't the one that closed this issue, but sure I can reopen it.

**Comment by xyklex** [comment] 2022-09-14 19:10
As mentioned by @salieri, this was a stopper for us to integrate with Athena and eventually Quicksight.

**Comment by henrymai** [comment] 2022-10-20 15:34
This will be in production by tonight, but the issue is fixed. For details on how to use the enhancements, refer to the screenshots in the associated pull requests above.

**Closed by henrymai** 2022-10-20 15:34 UTC
Labels: bug

**Comment by CharlesLuttos** [comment] 2022-10-25 12:12
Still stuck on this, trying to read a DocumentDB from Athena, but getting same errors, is there any work around?

**Comment by henrymai** [comment] 2022-10-25 13:37
@CharlesLuttos

Can you set the environment variable: `ATHENA_FEDERATION_SDK_LOG_LEVEL` to `debug` on your lambda connector and then rerun your query and paste the log output from your lambda here.

Additionally, can you tell me what version of the DocumentDB connector are you running, what other environment variables have you set on your lambda connector, and what your glue table parameters look like.

**Comment by CharlesLuttos** [comment] 2022-10-26 12:24
Right, we have tried to set `disable_projection_and_casing` to `true` also, now our environment variables are the following:
![image](https://user-images.githubusercontent.com/26559897/198025037-695789e9-d8f3-40b1-93be-c0925864de05.png)

Here also the version:
![image](https://user-images.githubusercontent.com/26559897/198025289-e711fa43-5b0f-4b8b-bc32-cdfc83cc42aa.png)

**Comment by CharlesLuttos** [comment] 2022-10-26 12:25
@henrymai , sorry, those tables does not appears in glue.

**Comment by henrymai** [comment] 2022-10-26 13:44
What is the actual error that you are getting?

There are two kinds of errors in this issue:
1) Not being able to query table names with upper casing in them
   - For this one you _must_ setup a glue table with the `sourceName` parameter in the glue table set up to your mongodb table/collection name, this is how we know what the actual table name is with the upper casing.

2) Not being able to return data for column names that have upper casing in them, this is what `disable_projection_and_casing` deals with.

I suspect your actual problem is (1), in which case as I mentioned above, you need to setup a Glue table.
Refer to the screenshots here: https://github.com/awslabs/aws-athena-query-federation/pull/803

**Comment by CharlesLuttos** [comment] 2022-10-28 18:15
Hello @henrymai thanks for helping us, we did a workaround, to verify better what is happening and we also changed some table and database names to lowercase, with this we realized a successful query in some tables through Athena, but some tables, with underscore, we got following error:
![image](https://user-images.githubusercontent.com/26559897/198704693-728fe998-1f0f-4c48-8019-067844973874.png)

**Comment by henrymai** [comment] 2022-10-28 18:58
Can you paste the debug logs for the DocumentDB Lambda Connector for that query here?

**Comment by CharlesLuttos** [comment] 2022-10-28 19:48
Sure:
![image](https://user-images.githubusercontent.com/26559897/198720254-a9da290f-bf38-49ca-b683-95e8ca54a120.png)

**Comment by henrymai** [comment] 2022-10-28 20:03
Do you have the rest of the logs? What you pasted is near the beginning of the lambda execution. We want to look for the log messages related to when its trying to look up your table with the underscore.

**Comment by CharlesLuttos** [comment] 2022-10-31 14:59
Hello, sorry for being late @henrymai , here is:

`

2022-10-31 12:46:25 5tcedsrd-efs5-4x17-bb94-71b6e2698a5x INFO  MetadataHandler:239 - doHandleRequest: request[GetTableRequest{queryId=08d3erb3-ba03-4u59-b8j7-df063c28bc78, tableName=TableName{schemaName=ground, tableName=test_ground}}]


2022-10-31 12:46:25 5tcedsrd-efs5-4x17-bb94-71b6e2698a5x WARN  DocDBMetadataHandler:197 - doGetTable: Unable to retrieve table[ground:test_ground] from AWS Glue.
com.amazonaws.services.glue.model.EntityNotFoundException: Database ground not found. (Service: AWSGlue; Status Code: 400; Error Code: EntityNotFoundException; Request ID: ed6fe0cf-cae7-49cc-bf67-925f2188d73a; Proxy: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1811) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1395) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1371) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530) ~[task/:?]
	at com.amazonaws.services.glue.AWSGlueClient.doInvoke(AWSGlueClient.java:8202) ~[task/:?]
	at com.amazonaws.services.glue.AWSGlueClient.invoke(AWSGlueClient.java:8169) ~[task/:?]
	at com.amazonaws.services.glue.AWSGlueClient.invoke(AWSGlueClient.java:8158) ~[task/:?]
	at com.amazonaws.services.glue.AWSGlueClient.executeGetTable(AWSGlueClient.java:4774) ~[task/:?]
	at com.amazonaws.services.glue.AWSGlueClient.getTable(AWSGlueClient.java:4745) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.GlueMetadataHandler.doGetTable(GlueMetadataHandler.java:385) ~[task/:?]
	at com.amazonaws.athena.connectors.docdb.DocDBMetadataHandler.doGetTable(DocDBMetadataHandler.java:192) [task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doHandleRequest(MetadataHandler.java:257) [task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:135) [task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:103) [task/:?]
	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:899) [aws-lambda-java-runtime-0.2.0.jar:?]
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:268) [aws-lambda-java-runtime-0.2.0.jar:?]
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:206) [aws-lambda-java-runtime-0.2.0.jar:?]
	at lambdainternal.AWSLambda.main(AWSLambda.java:200) [aws-lambda-java-runtime-0.2.0.jar:?]


2022-10-31 12:46:25 5tcedsrd-efs5-4x17-bb94-71b6e2698a5x INFO  DocDBMetadataHandler:204 - doGetTable: Inferring schema for table[TableName{schemaName=ground, tableName=test_ground}].


2022-10-31 12:46:26 bc7uxi8i-dfgv-trtg-bty7-esdb1asd00f4 WARN  SchemaUtils:258 - Unknown type[null] for field[address], defaulting to varchar.


2022-10-31 12:46:26 bc7uxi8i-dfgv-trtg-bty7-esdb1asd00f4 INFO  MetadataHandler:258 - doHandleRequest: response[GetTableResponse{tableName=TableName{schemaName=ground, tableName=test}, schema=Schema<_id: Utf8, name: Utf8, active: Bool, locality: Utf8, region: Utf8, address: Utf8>, partitionColumns=[], requestType=GET_TABLE, catalogName=GroundDev}]`

**Comment by CharlesLuttos** [comment] 2022-11-01 20:42
Hello, @henrymai , is it enough?

**Comment by CharlesLuttos** [comment] 2022-11-04 21:32
@henrymai , we have realized that there is some reading issue with tables inside databases with uppercase characters, and the environment variable suggested works only for column names.

At lambda log we see the above error pointing to a database in lowercase, but this one is set in CamelCase, there is a way to set lambda function to consider CamelCase database as we see in Athena, and how is also set in documentdb?

**Comment by henrymai** [comment] 2022-11-07 02:43
@CharlesLuttos 

So to first address your undescore problem from here: https://github.com/awslabs/aws-athena-query-federation/issues/463#issuecomment-1297218166

I am unable to reproduce your problem with underscores in the table name. I have attached my redacted lambda logs, screenshots of my configuration, and results from my own Athena query against docdb on a table with an underscore in the name.
[mongo_lambda_logs.csv](https://github.com/awslabs/aws-athena-query-federation/files/9947647/mongo_lambda_logs.csv)
![mongo_lambda_settings](https://user-images.githubusercontent.com/136857/200213733-37adf32a-174f-4ae8-a93e-c6b44993399b.png)
![mongo_test_csdf_table_athena_results](https://user-images.githubusercontent.com/136857/200213735-7dc2cffc-1543-4619-b2bf-47d1b9bcd6a1.png)

----

And in regards to your latest problem with mixed case database names: https://github.com/awslabs/aws-athena-query-federation/issues/463#issuecomment-1304278196

This is a current limitation (mainly with Athena itself) that we don't currently have plans to address. Please file a feature request to support mixed case schema names if this is something you need.

**Comment by aafaq-rashid-comprinno** [comment] 2024-08-14 07:43
**enable_case_insensitive_match** – (Optional) When **true**, performs case insensitive searches against schema and table names in Amazon DocumentDB. The default is false. Use if your query contains uppercase schema or table names.
