### ISSUE TITLE
[BUG] Using upper key database or table names  with connector Timestream fails

### ISSUE THREAD

**Issue by andasv** [awslabs/aws-athena-query-federation#792] opened 2022-10-09 09:56 UTC
**Describe the bug**
When using upper key database or table names  with connector Timestream fails:

GENERIC_USER_ERROR: Encountered an exception[com.amazonaws.services.timestreamquery.model.ValidationException] from your LambdaFunction[arn:aws:lambda:us-east-1:978572884825:function:timestreamathenaconnector] executed in context[retrieving meta-data] with message[The table 'iotmulti' does not exist in database 'testdb' at line 1:1 (Service: AmazonTimestreamQuery; Status Code: 400; Error Code: ValidationException; Request ID: BTC575JOI5ABUT6PB7PEPKVKY4; Proxy: null)]
This query ran against the "testdb" database, unless qualified by the query. 

**To Reproduce**
1. Create sample query for IoT Data in Amazon Timestream
2. Add Athena connector
3. Run query
SELECT * FROM "testdb"."IoTMulti" limit 10;

**Expected behavior**
Athena shall show the content of IoTMulti table

**Connector Details (please complete the following information):**
 - Version: 2022.39.1
 - Name timestream
 - Athena Query IDs BTC575JOI5ABUT6PB7PEPKVKY4

**Comment by hackett123** [comment] 2022-10-31 19:26
Hi [andasv](https://github.com/andasv), thanks for being patient here. I'm taking a look at this issue.

Can you confirm for us whether or not you are using Glue for your table metadata?

**Comment by hackett123** [comment] 2023-04-14 21:42
I got a chance to root cause this issue. The problem is that the Athena query engine, Trino, follows Hive naming semantics and will lower-case the schema name and table name in a query. (AWS Glue also follows this convention, so my earlier question is not important.)

What this means is that if you run a query such as `SELECT * FROM MySchema.MyTable`, when Trino receives the query, it converts your datasource name to `myschema.mytable`. When we then go to invoke your connector, we pass in `myschema.mytable`, which does not match the Timestream db/table name.

This can lead to confusing behavior, because when you run a DDL query such as `DESCRIBE MySchema.MyTable`, we will just directly invoke your lambda and pass in `MySchema.MyTable`, which will succeed, leading to confusion.

**The simplest workaround here is for users to make their timestream db and table names lowercase to conform with the current Hive-compliant semantics of the query engine.**

**Comment by hackett123** [comment] 2023-04-14 23:24
After conferring with @henrymai, I added a PR to address this automatically for customers so nobody has to change their schemas in Timestream. https://github.com/awslabs/aws-athena-query-federation/pull/1201

**Comment by hackett123** [comment] 2023-04-26 17:31
This is now merged, we will have it available to deploy from SAR after our next deployment, or users can simply upload the Timestream JAR to their Lambda today with the latest on master. I am going to close out this ticket.

**Closed by hackett123** 2023-04-26 17:31 UTC
Labels: bug
