### ISSUE TITLE
[BUG] Error while checking bucket ownership with connector athena-federation-jdbc to mysql

### ISSUE THREAD

**Issue by existeundelta** [awslabs/aws-athena-query-federation#288] opened 2020-11-07 06:18 UTC
GENERIC_USER_ERROR: Encountered an exception[java.lang.RuntimeException] from your LambdaFunction[arn:function:athena-federation-jdbc] executed in context[retrieving meta-data] with message[Error while checking bucket ownership for spill_bucket]

the query is executed in an account/Vpc and runs in a mysql in other account/vpc the vpcs are peer connected and correct security groups, and the queries runs (all related to schemas metadata work properly). The problem es when the query is executed it says this error, tried with two buckets one in each account and also proved with bucket in the account where athena query and lambda is with giving permissions to the other.

Lambda function has role rights to access this bucket(spill_bucket) and and for the one for athena results

mysql
java8

**Comment by avirtuos** [comment] 2020-11-07 15:09
Can you check the cloudsearch logs for the Lambda function, it should have a more detailed error with stack trace. I suspect that your Lambda is unable to contact S3 possibly due to lack of a route to S3 or no internet gateway. A quick way to test this theory is to add an S3 VPC endpoint to the subnet(s) your Lambda function is running in

**Comment by existeundelta** [comment] 2020-11-07 18:57
it says:
INFO SpillLocationVerifier:67 - Spill bucket has been changed from null to [spill_bucket_name]
WARN  CompositeHandler:104 - handleRequest: Completed with an exception.
java.lang.RuntimeException: Error while checking bucket ownership for [spill_bucket_name]
> Caused by: java.net.SocketTimeoutException: connect timed out	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_201]	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_201]	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_201]	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_201]	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_201]	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_201]	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:339) ~[task/:?]	at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:142) ~[task/:?]	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[task/:?]	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373) ~[task/:?]	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76) ~[task/:?]	at com.amazonaws.http.conn.$Proxy18.connect(Unknown Source) ~[?:?]	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) ~[task/:?]	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[task/:?]	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[task/:?]	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[task/:?]	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[task/:?]	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[task/:?]	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72) ~[task/:?]	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1286) ~[task/:?]	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1102) ~[task/:?]	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:759) ~[task/:?]	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:733) ~[task/:?]	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:715) ~[task/:?]	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:675) ~[task/:?]	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:657) ~[task/:?]	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:521) ~[task/:?]	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4705) ~[task/:?]	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4652) ~[task/:?]	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4646) ~[task/:?]	at com.amazonaws.services.s3.AmazonS3Client.listBuckets(AmazonS3Client.java:968) ~[task/:?]	at com.amazonaws.services.s3.AmazonS3Client.listBuckets(AmazonS3Client.java:974) ~[task/:?]	at com.amazonaws.athena.connector.lambda.domain.spill.SpillLocationVerifier.updateBucketState(SpillLocationVerifier.java:87) ~[task/:?]	... 10 more | 
2020-11-07 06:09:15 e2384cc2-aee8-4d7a-bfe7-181cb09f8c65 WARN CompositeHandler:104 - handleRequest: Completed with an exception. java.lang.RuntimeException: Error while checking bucket ownership for [spill_bucket_name] at com.amazonaws.athena.connector.lambda.domain.spill.SpillLocationVerifier.updateBucketState(SpillLocationVerifier.java:99) ~[task/:?] at com.amazonaws.athena.connector.lambda.domain.spill.SpillLocationVerifier.checkBucketAuthZ(SpillLocationVerifier.java:73) ~[task/:?] at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doHandleRequest(MetadataHandler.java:265) ~[task/:?] at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:132) ~[task/:?] at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:100) [task/:?] at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:902) [LambdaSandboxJava-1.0.jar:?] at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:341) [LambdaSandboxJava-1.0.jar:?] at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63) [LambdaSandboxJava-1.0.jar:?] at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201] at java.lang.Class.forName(Class.java:348) [?:1.8.0_201] at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:150) [LambdaJavaRTEntry-1.0.jar:?] Caused by: com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to s3.amazonaws.com:443 [s3.amazonaws.com/[IP] failed: connect timed out at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1164) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1110) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:759) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:733) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:715) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:675) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:657) ~[task/:?] at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:521) ~[task/:?] at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4705) ~[task/:?] at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4652) ~[task/:?] at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4646) ~[task/:?] at com.amazonaws.services.s3.AmazonS3Client.listBuckets(AmazonS3Client.java:968) ~[task/:?] at com.amazonaws.services.s3.AmazonS3Client.listBuckets(AmazonS3Client.java:974) ~[task/:?] at com.amazonaws.athena.connector.lambda.domain.spill.SpillLocationVerifier.updateBucketState(SpillLocationVerifier.java:87) ~[task/:?] ... 10 more Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to s3.amazonaws.com:443 [s3.amazonaws.com/IP] failed: connect timed out at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151) ~[task/:?] at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373) ~[task/:?] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201] at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201] at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76) ~[task/:?] at com.amazonaws.http.conn.$Proxy18.connect(Unknown Source) ~[?:?] at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) ~[task/:?] at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[task/:?] at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[task/:?] at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[task/:?] at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[task/:?] at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[task/:?] at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1286) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1102) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:759) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:733) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:715) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:675) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:657) ~[task/:?] at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:521) ~[task/:?] at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4705) ~[task/:?] at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4652) ~[task/:?] at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4646) ~[task/:?] at com.amazonaws.services.s3.AmazonS3Client.listBuckets(AmazonS3Client.java:968) ~[task/:?] at com.amazonaws.services.s3.AmazonS3Client.listBuckets(AmazonS3Client.java:974) ~[task/:?] at com.amazonaws.athena.connector.lambda.domain.spill.SpillLocationVerifier.updateBucketState(SpillLocationVerifier.java:87) ~[task/:?] ... 10 more Caused by: java.net.SocketTimeoutException: connect timed out at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_201] at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_201] at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_201] at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_201] at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_201] at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_201] at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:339) ~[task/:?] at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:142) ~[task/:?] at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[task/:?] at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373) ~[task/:?] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201] at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201] at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76) ~[task/:?] at com.amazonaws.http.conn.$Proxy18.connect(Unknown Source) ~[?:?] at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) ~[task/:?] at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[task/:?] at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[task/:?] at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[task/:?] at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[task/:?] at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[task/:?] at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1286) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1102) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:759) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:733) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:715) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:675) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:657) ~[task/:?] at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:521) ~[task/:?] at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4705) ~[task/:?] at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4652) ~[task/:?] at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4646) ~[task/:?] at com.amazonaws.services.s3.AmazonS3Client.listBuckets(AmazonS3Client.java:968) ~[task/:?] at com.amazonaws.services.s3.AmazonS3Client.listBuckets(AmazonS3Client.java:974) ~[task/:?] at com.amazonaws.athena.connector.lambda.domain.spill.SpillLocationVerifier.updateBucketState(SpillLocationVerifier.java:87) ~[task/:?] ... 10 more
-- | --
then
Error while checking bucket ownership for [spill_bucket_name]: java.lang.RuntimeException java.lang.RuntimeException: Error while checking bucket ownership for [spill_bucket_name]
Caused by: java.net.SocketTimeoutException: connect timed out
then
Exception in thread "main" java.lang.Error: java.lang.OutOfMemoryError: Metaspace

**Comment by avirtuos** [comment] 2020-11-07 19:30
Yes, the Lambda is running in a network (subnet) which has no route (path) to S3. Either because of no internet gateway or due to security groups, etc... Trying a box endpoint is the 'safest' way to test fixing it since there is virtually no risk you'd open up your VPC to unwanted traffic from the internet. The box endpoint would only allow traffic to/from S3.

**Comment by existeundelta** [comment] 2020-11-07 20:27
thanks!

**Comment by avirtuos** [comment] 2020-11-07 20:28
Did it work? Can we close the issue?

**Comment by existeundelta** [comment] 2020-11-07 20:30
still not proved is saturday night herer, having dinner with family ;)

**Comment by avirtuos** [comment] 2020-11-08 15:43
The console freezing only affects the left nav (it's a bug we are working on). You can still run queries.

**Comment by avirtuos** [comment] 2020-11-08 15:43
As for your permission error, you should not be using policies based on the endpoint Arn. That won't work especially since when Athena goes to read that dta it won't have access to that endpoint .

**Comment by existeundelta** [comment] 2020-11-08 16:26
yes, thanks, really now I delete the s3 endopoint (so also its policy), beacause get the error despite wat bucket name I put, so i get the same acces denied if i put a bucket name that don't exist... I'll try to reproduce the acces throw a ec2, so I can understant it better. 

> The console freezing only affects the left nav (it's a bug we are working on). You can still run queries.
ok, thanks, but really it affects all the tab (freeze the all the tab)

**Comment by avirtuos** [comment] 2020-11-08 16:28
It's causing the entire console to freeze for you?

**Comment by existeundelta** [comment] 2020-11-08 17:26
yes, the entire tab (chrome)

**Comment by existeundelta** [comment] 2020-11-09 07:32
how has to be the bucket name in spill_bucket for accesing it throw and endpoint in an VPC?
bucketname 
or bucketname.s3.region.amazon.com
or may be another
?
because i think the problem is that lambda is not Error while checking bucket ownership in the appropriate bucket

**Comment by kpkab** [comment] 2021-06-03 21:06
hi

Is this issue still open? Im trying to use Athena Federated Query to access data in RS Cluster and im getting the same error.

GENERIC_USER_ERROR: Encountered an exception[java.lang.RuntimeException] from your LambdaFunction[arn:aws:lambda:us-east-1:11111111111:function:lambdafunctionname] executed in context[retrieving meta-data] with message[Error while checking bucket ownership for my_spill_bucket_name]

**Comment by dectl** [comment] 2022-01-12 18:46
Same issue here...

**Comment by ianbrumby** [comment] 2023-01-27 21:16
Hello,

I was struggling with this error for a long time. It turns out that the Lambda Role needs permissions to List all the S3 Buckets in the account, not just the spill bucket.

**Closed** 2023-10-23 14:37 UTC
Labels: bug

**Comment by akuzin1** [comment] 2023-10-23 14:46
@ianbrumby is correct. This should however be accounted for by the default Lambda Execution Role. If issue persists, please open a new issue for better traceability. Thanks!

**Comment by evbo** [comment] 2024-01-15 00:23
@akuzin1 the problem is the lambda tries calling `listBuckets`. This can lead to a pretty big caveat because if you're in a private VPC there's no simple way to interact with buckets in other regions.

For instance, my connector might be setup in us-west-2 but there happens to also be buckets from us-west-1 in my account. Calling listBuckets will fail since my VPC endpoint for S3 must be in the same region as the lambda. Perhaps VPC peering could be setup, but that is a lot of complexity just to satisfy a listBuckets call.

**Comment by akuzin1** [comment] 2024-01-24 15:27
Thanks for reopening issue, will prioritize addressing ticket this week.
