### ISSUE TITLE
[BUG] Deterministic failure to process specific (large?) ListTablesResponse results in 3 retries, last one has malformed `schema` value of `null`

### ISSUE THREAD

**Issue by dvdotsenko** [awslabs/aws-athena-query-federation#260] opened 2020-09-29 03:19 UTC
For some specific `ListTablesResponse` payloads, Athena deterministically "chokes" on that payload, retries same request 3 more times, last one with malformed data, resulting in failure to handle the malformed request on Lambda side.

Example malformed request:

```
2020-09-29 01:35:06 34a393bd-2cc1-4e9b-9f70-b032213a69ce INFO  CompositeHandler:54 - Raw Request: 
{
    "@type": "ListTablesRequest",
    "identity": {
        "id": "UNKNOWN",
        "principal": "UNKNOWN",
        "account": "897117390337",
        "arn": "arn:aws:iam::897117390337:user/ddotsenko",
        "tags": {},
        "groups": []
    },
    "queryId": "3308d3d3-5746-4218-ba14-811f4cb38840",
    "catalogName": "my",
    "schemaName": null  <-----------------------------------------------
}
```

(I don't have access to Athena-side errors. Only assume there are some based on Athena retrying the same request)

Reliably **Successful query** (Returns 91 tables, at least 12k of data (`.toString()` size of response object is 11k):
```
select table_schema, table_name
from my.information_schema.tables
where table_schema = 'unite__operam_test'
```

Reliably **Failing query** (returns 343 tables, at least 25k of data (`.toString()` size of response object is 22k) (full `.toString()` serialized response is on the bottom of this ticket):
```
select table_schema, table_name
from my.information_schema.tables
where table_schema = 'panoramic_sandbox_bcxm5512__central_perk'
```

Initial and retry request / response summary:

```
// Incoming Ping request
2020-09-29 01:35:02 900a7832-4e0d-4232-aca3-30c1cb4ba220 INFO  CompositeHandler:54 - Raw Request: 
{
    "@type": "PingRequest",
    "identity": {
        "id": "UNKNOWN",
        "principal": "UNKNOWN",
        "account": "897117390337",
        "arn": "arn:aws:iam::897117390337:user/ddotsenko",
        "tags": {},
        "groups": []
    },
    "catalogName": "my",
    "queryId": "3308d3d3-5746-4218-ba14-811f4cb38840"
}
// Incoming ListTablesRequest
2020-09-29 01:35:02 3e9b3ff1-260a-43ea-a2b7-e6206de47638 INFO  CompositeHandler:54 - Raw Request: 
{
    "@type": "ListTablesRequest",
    "identity": {
        "id": "UNKNOWN",
        "principal": "UNKNOWN",
        "account": "897117390337",
        "arn": "arn:aws:iam::897117390337:user/ddotsenko",
        "tags": {},
        "groups": []
    },
    "queryId": "3308d3d3-5746-4218-ba14-811f4cb38840",
    "catalogName": "my",
    "schemaName": "panoramic_sandbox_bcxm5512__central_perk"
}
// Outgoing ListTablesResponse
2020-09-29 01:35:03 3e9b3ff1-260a-43ea-a2b7-e6206de47638 INFO  MetadataHandler:244 - doHandleRequest: response[ListTablesResponse{tables=[TableName{schemaName=panoramic_sandbox_bcxm5512__central_perk, tableName=board377__AppNexus__chart1773__AppNexus_Overview}, TableName{schemaName=panoramic_sandbox_bcxm5512__central_perk, tableName=board377__AppNexus__chart1776__AppNexus_Display_Native_Overview},...]}]

// Incoming ListTablesRequest RETRY #1
2020-09-29 01:35:03 116eb904-9110-4c01-92ae-ab1ef3b44c08 INFO  CompositeHandler:54 - Raw Request: 
{
    "@type": "ListTablesRequest",
    "identity": {
        "id": "UNKNOWN",
        "principal": "UNKNOWN",
        "account": "897117390337",
        "arn": "arn:aws:iam::897117390337:user/ddotsenko",
        "tags": {},
        "groups": []
    },
    "queryId": "3308d3d3-5746-4218-ba14-811f4cb38840",
    "catalogName": "my",
    "schemaName": "panoramic_sandbox_bcxm5512__central_perk"
}
// Outgoing ListTablesResponse AGAIN (same payload)
2020-09-29 01:35:04 116eb904-9110-4c01-92ae-ab1ef3b44c08 INFO  MetadataHandler:244 - doHandleRequest: response[ListTablesResponse{tables=[TableName{schemaName=panoramic_sandbox_bcxm5512__central_perk, tableName=board377__AppNexus__chart1773__AppNexus_Overview}, TableName{schemaName=panoramic_sandbox_bcxm5512__central_perk, tableName=board377__AppNexus__chart1776__AppNexus_Display_Native_Overview}, TableName{schemaName=panoramic_sandbox_bcxm5512__central_perk, tableName=board377__AppNexus__chart2000__AppNexus_Video_CTV_Overview},....

// Incoming ListTablesRequest RETRY #2
2020-09-29 01:35:04 4e14ffc9-a856-4422-9ebc-a1456047047d INFO  CompositeHandler:54 - Raw Request: 
{
    "@type": "ListTablesRequest",
    "identity": {
        "id": "UNKNOWN",
        "principal": "UNKNOWN",
        "account": "897117390337",
        "arn": "arn:aws:iam::897117390337:user/ddotsenko",
        "tags": {},
        "groups": []
    },
    "queryId": "3308d3d3-5746-4218-ba14-811f4cb38840",
    "catalogName": "my",
    "schemaName": "panoramic_sandbox_bcxm5512__central_perk"
}
// Outgoing ListTablesResponse AGAIN (same payload)
2020-09-29 01:35:05 4e14ffc9-a856-4422-9ebc-a1456047047d INFO  MetadataHandler:244 - doHandleRequest: response[ListTablesResponse{tables=[TableName{schemaName=panoramic_sandbox_bcxm5512__central_perk, tableName=board377__AppNexus__chart1773__AppNexus_Overview}, TableName{schemaName=panoramic_sandbox_bcxm5512__central_perk, tableName=board377__AppNexus__chart1776__AppNexus_Display_Native_Overview}, TableName{schemaName=panoramic_sandbox_bcxm5512__central_perk, tableName=board377__AppNexus__chart2000__AppNexus_Video_CTV_Overview}...

// Incoming ListTablesRequest RETRY #3, malformed
2020-09-29 01:35:06 34a393bd-2cc1-4e9b-9f70-b032213a69ce INFO  CompositeHandler:54 - Raw Request: 
{
    "@type": "ListTablesRequest",
    "identity": {
        "id": "UNKNOWN",
        "principal": "UNKNOWN",
        "account": "897117390337",
        "arn": "arn:aws:iam::897117390337:user/ddotsenko",
        "tags": {},
        "groups": []
    },
    "queryId": "3308d3d3-5746-4218-ba14-811f4cb38840",
    "catalogName": "my",
    "schemaName": null   <--------------------------------------------------------
}
```

Done with DataGrip + AthenaJDBC42_2.0.14.jar driver. 
Retries don't originate in JDBC driver. I don't see retries in JDBC logs. Logs Attached:

[AthenaJDBC_Driver.log](https://github.com/awslabs/aws-athena-query-federation/files/5296145/AthenaJDBC_Driver.log)

[AthenaJDBC_Connection_1.log](https://github.com/awslabs/aws-athena-query-federation/files/5296146/AthenaJDBC_Connection_1.log)

`.toString()`-serialized `ListTablesResponse` object for failing query:

[2265e70b-0965-40cd-a0a7-5d2e5e_2020-09.txt](https://github.com/awslabs/aws-athena-query-federation/files/5296156/2265e70b-0965-40cd-a0a7-5d2e5e_2020-09.txt)

**Comment by hackett123** [comment] 2023-04-26 23:41
This ticket was opened in September 2020. Much of the implementation in our JDBC connectors has changed since then. For example, from the logs attached on this ticket I can see that the queries were using the Athena Simba JDBC driver, which we no longer use for our JDBC connectors. (I didn't know we ever used it).

The details in the ticket suggest that the retries occur more frequently on larger schemas, suggesting pagination would help here, and that the `schemaName` can be null after failing multiple retries on these larger schemas.

With regards to pagination, this was added to the SDK for ListTables calls in April 2021. Unfortunately, JDBC does not allow for pagination in its statements. What this means is that in order to paginate requests against JDBC connectors, the actual statement we send would need a clause that specifies which chunk of data we want. This functionality is not available for all JDBC data stores, and even amongst the ones it exists for, the syntax is different. For example, some need a `rownum()` function with subqueries and a predicate against a range, and others just need a `limit` and `offset` clause.

I also cannot reproduce the issue, because I cannot determine what connector the customer was using for this ticket.

Because so much has changed in the JDBC connectors since the opening of this ticket, it does not seem valuable to add this pagination for some of our JDBC connectors without data suggesting it remains a problem today seeing as it is not trivial to add. So, I will wait a week and then close this ticket unless there are any followups.

**Comment by hackett123** [comment] 2023-05-02 22:40
Will close out this ticket for now.

**Closed by hackett123** 2023-05-02 22:40 UTC
Labels: bug
