### ISSUE TITLE
[FEATURE] Expose IAM customizations in SAM templates

### ISSUE THREAD

**Issue by davidaah** [awslabs/aws-athena-query-federation#365] opened 2021-03-05 18:05 UTC
**Is your feature request related to a problem? If yes, please describe.**

Currently the published Athena connectors do not support bringing your own role or providing an IAM permissions boundary ARN. This limits the ability to consume these connectors in a governed environment where application develops do not have access to create arbitrary IAM roles

**Describe the solution you'd like**

Each template should expose two additional parameters corresponding to the 'AWS::Serverless::Function' resource, specifically the `Role` and `PermissionsBoundary` attributes (see https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html for more details). 

**Describe alternatives you've considered**

The only workaround we have currently would be to fork the repo, make manual modifications to the configuration yaml and re-publish in to a private serverless application repository in our accounts.

**Additional context**

N/A

**Comment by tkcmada** [comment] 2021-03-05 23:45
👍

**Comment by victorfeight** [comment] 2023-01-27 21:45
Hello Team. Any updates on when a custom LambdaRole parameter would be available for usage in the PostgreSQL connector? https://github.com/awslabs/aws-athena-query-federation/tree/master/athena-postgresql

Otherwise, if there's a custom working SAM template with the Role included, I could try to deploy to Serverless Application Repository. I wasn't able to adapt the DynamoDB connector's LambdaRole parameter to a custom yaml template, facing:
Error: [InvalidTemplateException('Every Condition member must be a string.')] Every Condition member must be a string.

Attached is my go at it:
[template.yml.txt](https://github.com/awslabs/aws-athena-query-federation/files/10523339/template.yml.txt)

**Comment by henrymai** [comment] 2023-01-27 21:56
@victorfeight 

In the `template.yml.txt` that you attached, it looks like the issue is due to this:

```
Condition: !Not HasLambdaRole
```

Instead of doing it this way:

```
Condition: NotHasLambdaRole
```

I've seen that error myself before when I also tried to use the condition like `!Not HasLambdaRole`, which is why the condition is now `NotHasLambdaRole` instead.

**Comment by victorfeight** [comment] 2023-01-28 01:05
Thank you, that did help.

**Comment by henrymai** [comment] 2023-01-28 01:34
@victorfeight 

Glad to hear it works for you.

Also feel free to submit a pull request if you think your changes are general enough to be used by everyone else too (NOTE: I didn't do a diff with your example so I don't know if it is general or not).

**Comment by victorfeight** [comment] 2023-01-28 01:55
Sure, I've updated it to be more general. Got it successfully deployed, just testing with and without a custom roleArn and then I can submit the pull request.

**Comment by henrymai** [comment] 2023-01-28 06:13
Thanks for working on this and testing it as well @victorfeight.
Looking forward to the pull request.

**Comment by victorfeight** [comment] 2023-01-28 07:04
No worries. I've got it successfully working with both custom role, and without. I'll keep it in Serverless Application Repository as AthenaPostgreSQLConnector-roles until it can be merged. Will create a pull request momentarily.

**Comment by victorfeight** [comment] 2023-01-28 07:31
@henrymai Have created the pull request here: https://github.com/awslabs/aws-athena-query-federation/pull/995

Let me know if there's anything I should modify, but it's working well in the deployment, and can query tables with/without selecting the custom role.

**Comment by ned9** [comment] 2023-02-24 00:56
hey @henrymai I've created a PR that extends the same enhancement as above for athena-postgresql connector (adding a `LambdaRoleARN` param) to the athena-mysql and athena-sqlserver connectors. If this is something you'd consider accepting, would love a review :)

**Comment by henrymai** [comment] 2023-03-28 14:56
Closing this ticket out since the pull requests have been reviewed and merged already.

**Closed by henrymai** 2023-03-28 14:56 UTC
Labels: enhancement
