### ISSUE TITLE
[BUG] NPE in schema detection with connector DynamoDB

### ISSUE THREAD

**Issue by ankurgupta4891** [awslabs/aws-athena-query-federation#118] opened 2020-02-26 23:14 UTC
**Describe the bug**
Having a null value filed in Map attribute will throw NPE when connector tries to generate schema. Connector also stops processing other DDB tables and Athena does not list any tables under DDB catalog.

**To Reproduce**
1. Create a DynamoDB table with the following item:
```
{
  "id": "foo",
  "some_object": {
    "field1": 456,
    "field2": null
  }
}
```
2. Use a DynamoDB connector from Athena and receive the following error:

```
CompositeHandler:104 - handleRequest: Completed with an exception.
java.lang.NullPointerException: null
 at com.amazonaws.athena.connectors.dynamodb.util.DDBTypeUtils.inferArrowField(DDBTypeUtils.java:136) ~[task/:?]
 at com.amazonaws.athena.connectors.dynamodb.util.DDBTypeUtils.inferArrowField(DDBTypeUtils.java:123) ~[task/:?]
 at com.amazonaws.athena.connectors.dynamodb.util.DDBTableUtils.peekTableForSchema(DDBTableUtils.java:145) ~[task/:?]
 at com.amazonaws.athena.connectors.dynamodb.resolver.DynamoDBTableResolver.getTableSchema(DynamoDBTableResolver.java:116) ~[task/:?]
 at com.amazonaws.athena.connectors.dynamodb.DynamoDBMetadataHandler.doGetTable(DynamoDBMetadataHandler.java:240) ~[task/:?]
 at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doHandleRequest(MetadataHandler.java:243) ~[task/:?]
 at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:132) ~[task/:?]
 at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:100) [task/:?]
 at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:906) [LambdaSandboxJava-1.0.jar:?]
```

**Additional context**
NPE happens due to null value here -> https://github.com/atennak1/aws-athena-query-federation/blob/aa8009f5fd88c5ba17c8f1b74323adaebe381406/athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/util/DDBTypeUtils.java#L136

**Comment by avirtuos** [comment] 2020-02-26 23:21
This is expected, though the error message has been improved in the lastest commit. We recommend you explicitly define the schema of the table in Glue and not rely on schema inference since we can not infer schema from nulls. 

One more question, just incase there is another bug here that I am missing. Are there any rows without the null or do a minority of rows have the null? I ask because maybe we could be less sensitive to the null if other rows have real values there.

**Comment by ankurgupta4891** [comment] 2020-02-27 00:55
There are only few rows with non-null value. The use case for actual Map attribute is to store changes in some managed fields where fields are keys and their updates are values in the Map attribute. Unless all the fields are updated in single update, the map attribute would have keys with null value.

It silently fails in Athena console and doesn't show any table or pops-up the exception. I had to check lambda cloudwatch logs to figure out what's going wrong.

**Comment by avirtuos** [comment] 2020-02-27 01:01
I'm surprised you get a silent failure. When I try to replicate i get an error in the console. What browser are you using? And can you share a query id where it happened?

Lastly, let me know if you can try manually creating the table in Glue. The DDB connector will favor the schema from Glue over its own schema inference.

**Comment by ankurgupta4891** [comment] 2020-02-27 17:51
Query ID: 8474564f-4488-46f8-9488-440941b840a4
Browser: Chrome 
Version: 80.0.3987.122

**Comment by ankurgupta4891** [comment] 2020-02-27 17:58
I create glue crawler for my test table that had one record
```
{
  "ID": "1",
  "MapField": {
    "Field1": null
  }
}
```
The crawler added the table successfully with schema:
```
mytesttable
    mapfield (struct<Field1:varchar>)
    id (varchar)
```

But now, connector didn't fetch the data and I see no value in both id and mapfield columns in Athena console.. Below are CloudWatch logs from connector. 

```
2020-02-27 17:44:04 8a5592b5-37e1-465d-9866-b0a705ef9d40 INFO  RecordHandler:158 - doHandleRequest: response[ReadRecordsResponse{records=Block{rows=1, mapfield=[{[Field1 : null]}], id=[null]}, requestType=READ_RECORDS, catalogName=ddb}]
```

**Comment by avirtuos** [comment] 2020-02-27 20:29
Thanks for the update. I'll work to get this analysis and hopefully a fix or doc update prioritized.

**Comment by avirtuos** [comment] 2020-02-27 20:30
@soojinj Do you have capacity to take a look at this? I know you've been looking into the DDB connector a lot of late so may be opportunity for you to take on this item.

**Comment by soojinj** [comment] 2020-03-02 19:45
Hi @ankurgupta4891, I wanted to confirm that the columnMapping was added to the glue table once it was registered (Optional table property/parameter columnName https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-dynamodb/README.md ) I see that there are some case differences between the ddb column names vs glue column name (ID vs id for example).

**Comment by ankurgupta4891** [comment] 2020-03-02 20:17
Ah, I didn't. Now the query works in Athena console after adding columnMapping. Thanks.

**Comment by soojinj** [comment] 2020-03-02 22:31
@ankurgupta4891  when you were getting NPE with older commit, what did your ddb entry look like for

`{
  "id": "foo",
  "some_object": {
    "field1": 456,
    "field2": null
  }
}`

**Comment by ankurgupta4891** [comment] 2020-03-02 23:54
Earlier, I did not add tables in glue catalog and was letting the connector to auto-discover table schema. I could reproduce it every time when DDB record had null value for field in a Map attribute. It didn't matter how ddb entry look like (lowercase or uppercase), since I was not using Glue catalog.
```
{
  "ID": "1",
  "MapField": {
    "Field1": null
  }
}
```
The above was my DDB entry when NPE happened and later, I added table to glue catalog.

**Comment by soojinj** [comment] 2020-03-03 15:31
Re: I could reproduce it every time when DDB record had null value for field in a Map attribute.
    I am curious to know your exact repro steps to insert a null value in ddb, aside from NPE/glue table.

**Comment by ankurgupta4891** [comment] 2020-03-03 18:06
```json
aws dynamodb put-item --table-name MyTestTable --item \
'{
     "ID": {
         "S": "2"
     },
     "MapField": {
         "M": {
              "Field1": {
                   "NULL": true
               }
          }
     }
}'
```

**Comment by soojinj** [comment] 2020-03-04 16:40
Resolving the issue as the NPE is now being exposed with better error message with recent changes. The workaround was to register the table in Glue.

**Closed by soojinj** 2020-03-04 16:40 UTC
Labels: bug
