### ISSUE TITLE
[BUG] Querying bigquery from multiple projects with one service account

### ISSUE THREAD

**Issue by asa-bell** [awslabs/aws-athena-query-federation#845] opened 2022-12-01 07:48 UTC
I need to query bigquery from multiple projects via athena.

I have generated a service account in project_A and authorized this service account to access bigquery in project_B.
In lambda's environment variable, I specified gcp_project_id as project_B.
After the configuration in athena, I can see the datasets, databases, and tables in project_B in the athena console.
But when I query the data of project_B with SQL, I get the error: The specified dataset is not found in project_A.

In the "project history" of bigquery, I see that the query is in project_A. The project is not specified in SQL.

Any help is appreciated.

**Comment by jason-pixl** [comment] 2022-12-06 06:21
### Problem analysis

The problem should be in the aws-athena-query-federation repository.

The latest master branch(332ff5fb5ef72ef9f5847c0a7b15a11b80ec5b54) and v2022.47.1(tag), the problem should exist

The bug will occur while using the different configuration method when using aws-athena-query-federation: the same SecretNamePrefix corresponds to multiple GCPProjectIDs

### Code analysis

The following codes are analyzed and modified based on master branch

(git commit id: 332ff5fb5ef72ef9f5847c0a7b15a11b80ec5b54)

The code does not explicitly execute setProjectId when initializing BigQuery, but the projectId calculated by SecretNamePrefix

When initializing BigQuery, java-bigquery provides a method to set projectId, but it does not use

When querying datasets, databases, and tables, the projectId is explicitly set, so it can work normally.

However, when performing SQL query, the projectId is not set. After studying the source code of java-bigquery, when executing the SQL statement, the projectId will be obtained from BigQuery, and then the SQL statement will be executed.

```
public static BigQuery getBigQueryClient() throws IOException
{
    BigQueryOptions.Builder bigqueryBuilder = BigQueryOptions.newBuilder();
    String endpoint = System.getenv(BigQueryConstants.BIG_QUERY_ENDPOINT);
    if (StringUtils.isNotEmpty(endpoint)) {
        bigqueryBuilder.setHost(endpoint);
    }

    bigqueryBuilder.setCredentials(getCredentialsFromSecretsManager());
    return bigqueryBuilder.build().getService();
}
```

**Comment by henrymai** [comment] 2022-12-06 07:54
Hi @asa-bell 

I think I know what the problem is, can you confirm if your project names have mixed casing or if they are all lower case?

**Comment by henrymai** [comment] 2022-12-06 16:30
Fix has been merged: https://github.com/awslabs/aws-athena-query-federation/commit/8d952c40d1371273fa55f91f356344f5ead65244

I will update this issue again when we make a new release containing this fix.

**Comment by henrymai** [comment] 2022-12-16 01:31
Hi @asa-bell 

2022.50.1 was released yesterday night and contains the fix for this issue. Thanks again for raising this issue.

**Closed by henrymai** 2022-12-16 01:31 UTC
Labels: question
