### ISSUE TITLE
[BUG] Using Primary Key with Uppercase column names fails with connector PostgreSQL

### ISSUE THREAD

**Issue by hugorozestraten** [awslabs/aws-athena-query-federation#234] opened 2020-08-07 12:26 UTC
**Describe the bug**
When adding a PK to a postgresql table, Athena federated query fails with a generic error, then it shows an error related to the pK column on CloudWatch logs. 

**To Reproduce**
1. Create federation with postgreSQL on Athena;
2. Go to your PostgreSQL and create a table without a PK, using large name for columns using "_" character;
3. Query the table using Athena and it works;
4. Add a primary key on the Table;
5. Query the table using Athena and it will fail;

PosgreSQL ddl:
CREATE TABLE petro.for_athena_bad
(
   "ABABA_A_PANTA_CNJUNTAESAA"  numeric(38,10)   NOT NULL,
   "TBBSA_SQ_IDRENT_TROCHE"     numeric(38,10),
   "POCU_CD_PUCO"               numeric(38,10)
);

ALTER TABLE petro.for_athena_bad
   ADD CONSTRAINT pk_for_athena_bad
   PRIMARY KEY ("ABABA_A_PANTA_CNJUNTAESAA");

Without the PK it works.

**Expected behavior**
Perform queries on PostgreSQL tables with Primary keys, using Athena federated query.

**Screenshots / Exceptions / Errors**
If applicable, add screenshots, exception stack traces, or error messages to help explain your problem.  Stack traces for exceptions thrown by your Connector can be found in CloudWatch Logs under the 'aws/lambda/<Lambda_function_name>' log group.

2020-08-07 12:22:53 90c96ab9-0b6a-4524-9cff-ab4fafde4e79 WARN  CompositeHandler:104 - handleRequest: Completed with an exception.
java.lang.RuntimeException: 0: ERROR: column "ababa_a_panta_cnjuntaesaa" does not exist
  Position: 12
	at com.amazonaws.connectors.athena.jdbc.manager.JdbcMetadataHandler.getSplitClauses(JdbcMetadataHandler.java:313) ~[task/:?]
	at com.amazonaws.connectors.athena.jdbc.postgresql.PostGreSqlMetadataHandler.doGetSplits(PostGreSqlMetadataHandler.java:167) ~[task/:?]
	at com.amazonaws.connectors.athena.jdbc.MultiplexingJdbcMetadataHandler.doGetSplits(MultiplexingJdbcMetadataHandler.java:140) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doHandleRequest(MetadataHandler.java:260) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:132) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:100) [task/:?]
	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:902) [LambdaSandboxJava-1.0.jar:?]
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:341) [LambdaSandboxJava-1.0.jar:?]
	at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63) [LambdaSandboxJava-1.0.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_201]
	at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:150) [LambdaJavaRTEntry-1.0.jar:?]
Caused by: org.postgresql.util.PSQLException: ERROR: column "ababa_a_panta_cnjuntaesaa" does not exist
  Position: 12
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497) ~[task/:?]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233) ~[task/:?]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310) ~[task/:?]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446) ~[task/:?]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370) ~[task/:?]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:311) ~[task/:?]
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:297) ~[task/:?]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:274) ~[task/:?]
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:225) ~[task/:?]
	at com.amazonaws.connectors.athena.jdbc.manager.JdbcMetadataHandler.getSplitClauses(JdbcMetadataHandler.java:296) ~[task/:?]
	... 11 more
**Connector Details (please complete the following information):**
 - Version: current deployment at 2020.08.07
 - Name jdbc - postgreSQL
 - Athena Query IDs : 5c94f35f-7a05-452f-bbb0-b3989a8d98b3.

**Additional context**

**Comment by avirtuos** [comment] 2020-08-07 13:01
Unfortunately we can not presently support upper case column or table names since Athena itself is case insensitive and case information is lost. In some connectors we've worked around this by creating a mapping system. We've not yet done that for the jdbc connector.

The master issue for case sensitivity is #61 . I'm resolving this as a duplicate of that and adding your info there.

**Closed by avirtuos** 2020-08-07 13:01 UTC
Labels: bug
