### ISSUE TITLE
[BUG] TIime in the future with connector timestream

### ISSUE THREAD

**Issue by AmizerAWS** [awslabs/aws-athena-query-federation#768] opened 2022-08-30 10:11 UTC
**Describe the bug**

**To Reproduce**
Load any data to timestream with timestamp in milliseconds, deploy the connector and query this data via Athena and you will receive some of the timestamp appearing in the future

**Expected behavior**
Time for some of the data pulled from timestream shows in the future - like 2/3 days ahead

**Connector Details (please complete the following information):**
2022.34.1

**Additional context**

**Comment by ahom** [comment] 2022-08-30 16:49
**Root cause**
The bug seems to be due to the usage of 9 "S" in SimpleDateFormat used for time deserialization [here](https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-timestream/src/main/java/com/amazonaws/athena/connectors/timestream/TimestreamRecordHandler.java#L75)

When the timestamp includes milliseconds, SimpleDateFormat does the following calculation when using the 9 "S":

With the following timestamp 2022-08-30 12:58:53.544000000  == 1661857133544
It does calculation 2022-08-30 12:58:53 + 544000 seconds == 1662401133 == 2022-09-05 20:05:33

**Potential fix**
One fix would be to use DateTimeFormatter instead of SimpleDateFormat like [this example](https://github.com/awslabs/amazon-timestream-tools/blob/mainline/sample_apps/java/src/main/java/com/amazonaws/services/timestream/QueryExample.java#L27)

**Reproduction**
A simple demonstration of this issue can be seen with this simple reproduction: (https://www.jdoodle.com/online-java-compiler/)

```
import java.time.format.DateTimeFormatter;
import java.text.SimpleDateFormat;

public class MyClass {
    public static void main(String args[]) {
      String t = "2022-08-30 12:58:53.544000000";
      
      DateTimeFormatter JDBC_TIMESTAMP_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss.SSSSSSSSS");
      SimpleDateFormat ATHENA_TIMESTAMP_FORMATTER = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSSSSSSSS");
      try {

        System.out.println(JDBC_TIMESTAMP_FORMATTER.parse(t).toString());
        System.out.println(ATHENA_TIMESTAMP_FORMATTER.parse(t).toString());
      } catch (Exception e) {
      }
    }
}
``` 

Results:
```
{},ISO resolved to 2022-08-30T12:58:53.544
Mon Sep 05 20:05:33 GMT 2022
```

**Comment by hackett123** [comment] 2022-08-30 17:20
Thanks for the useful info. Just waiting on the query string used in Athena to solidify the context of the problem.

**Comment by ahom** [comment] 2022-08-30 20:05
This is the query of the **same data point**, with the timestamp I gave as example above:
* First one is directly from Timestream
* Second is through Athena connector to Timestream

![image](https://user-images.githubusercontent.com/1757140/187532259-13aa8b85-b2ea-441b-ad1b-d3c7f3c31337.png)
![image](https://user-images.githubusercontent.com/1757140/187532518-ad5027da-2594-468b-bb3f-1197c09f9fcc.png)

**Comment by Sagar-Chudamani** [comment] 2023-02-01 06:37
@AmizerAWS Did you find any fix or an efficient conversion function to fix this for now?

**Comment by henrymai** [comment] 2023-02-02 12:54
@Sagar-Chudamani @ahom @AmizerAWS

@nauy2697 has released a new version of the Timestream connector (2023.5.4) with his fix.
Closing out this ticket now. Reopen it if there's still a problem with this new version.

**Closed by henrymai** 2023-02-02 12:54 UTC
Labels: bug
