### ISSUE TITLE
JDBC AWS Secrets Replacement Needs Escaping

### ISSUE THREAD

**Issue by sdorazio** [awslabs/aws-athena-query-federation#79] opened 2019-12-11 15:33 UTC
Passwords retrieved from AWS Secrets Manager that contain escape sequences for Java Regex replacements cause the following exception:

```
java.lang.IllegalArgumentException: Illegal group reference
	at java.util.regex.Matcher.appendReplacement(Matcher.java:857)
	at java.util.regex.Matcher.replaceAll(Matcher.java:955)
	at com.amazonaws.connectors.athena.jdbc.connection.GenericJdbcConnectionFactory.getConnection(GenericJdbcConnectionFactory.java:92)
	at com.amazonaws.connectors.athena.jdbc.manager.JdbcMetadataHandler.doGetTable(JdbcMetadataHandler.java:205)
	at com.amazonaws.connectors.athena.jdbc.MultiplexingJdbcMetadataHandler.doGetTable(MultiplexingJdbcMetadataHandler.java:113)
	at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doHandleRequest(MetadataHandler.java:243)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:132)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:100)
	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:906)
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:341)
	at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:114)
```

Replacements needs to use `Pattern.quote` to avoid this.

**Comment by avirtuos** [comment] 2019-12-11 15:40
@sdorazio any chance you have a pull request with an example of the fix and a sample string that causes the error? This may allow us to test and merge a fix more quickly for you. If not, that's ok as one of our engineers will reproduce and fix as needed. @abhijeetvg I'll assign this to you and you can let me know if you don't have capacity for this and we will reassign.

**Comment by avirtuos** [comment] 2019-12-11 15:41
Ah I didn't see the PR on mobile. Thanks @sdorazio

**Comment by avirtuos** [comment] 2020-01-06 21:06
I raised a new PR because an erroneous suggestion I made resulted in an error in PR #80

**Comment by atennak1** [comment] 2020-01-06 21:22
Merged in https://github.com/awslabs/aws-athena-query-federation/pull/80

**Closed by atennak1** 2020-01-06 21:22 UTC
Labels: bug
