### ISSUE TITLE
[BUG] AthenaMySQLConnector can't handle table names with uppercase letters

### ISSUE THREAD

**Issue by daniel-hepworth** [awslabs/aws-athena-query-federation#1270] opened 2023-05-15 21:34 UTC
When querying an Aurora DB or MySQL table through the AthenaMySQLConnector in Athena, Athena generates the following error:

GENERIC_USER_ERROR: Encountered an exception[java.lang.RuntimeException] from your LambdaFunction[<lambda arn] executed in context[retrieving meta-data] with message[Could not find table in<database name>]

**To Reproduce after deploying connector**
1. In Athena run a query against a table with uppercase letters in the name.
2. Error is generated in the query response.

**Expected behavior**
When running a query against an Aurora or MySQL table with uppercase letters in the name it would return the queried data correctly.

**Screenshots / Exceptions / Errors**
If applicable, add screenshots, exception stack traces, or error messages to help explain your problem.  Stack traces for exceptions thrown by your Connector can be found in CloudWatch Logs under the 'aws/lambda/<Lambda_function_name>' log group.

**Connector Details (please complete the following information):**
- Connector: arn:aws:serverlessrepo:us-east-1:292517598671:applications/AthenaMySQLConnector 
- Version: serverlessrepo:semanticVersion | 2023.16.2
 - Name AthenaMySQLConnector

**Additional context**
It appears that the DynamoDB connector had similar issues, but have had a fix applied as well.

**Comment by hackett123** [comment] 2023-05-15 21:58
This will be addressed by @dbadaya1 - issue https://github.com/awslabs/aws-athena-query-federation/issues/61 was just assigned and covers the same issue.

**Comment by dbadaya1** [comment] 2023-05-24 21:26
Resolving as duplicate of https://github.com/awslabs/aws-athena-query-federation/pull/1289

**Closed by dbadaya1** 2023-05-24 21:26 UTC
Labels: bug
